version: '3'

services:

  frontend:
    build:
      context: ./nextjs-frontend
      args:
        NEXT_PUBLIC_GRAPHQL_API_URI: 'https://easy-deep-learning.org/graphql'
        NEXT_PUBLIC_GRAPHQL_API_URI_SSR: 'https://backend:1337/graphql'
        NODE_ENV: production
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.0-alpine
    volumes:
      - ./nginx/config/nginx.production.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  backend:
    build:
      context: ./strapi-backend
      args:
        NODE_ENV: production
    ports:
      - "1337:1337"
